// <auto-generated />
using System;
using CC.Infrastructure.Persistences.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220234153_EditTable")]
    partial class EditTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("CC.Domain.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AuditCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditCreateUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditDeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditDeleteUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditUpdateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("CC.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AuditCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditCreateUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditDeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditDeleteUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditUpdateUser")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("CC.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuditCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditCreateUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditDeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditDeleteUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditUpdateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CC.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AuditCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditCreateUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditDeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditDeleteUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditUpdateUser")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("CC.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuditCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditCreateUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditDeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditDeleteUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditUpdateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CC.Domain.Entities.Permission", b =>
                {
                    b.HasOne("CC.Domain.Entities.Feature", "Feature")
                        .WithMany("AvailablePermissions")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("CC.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("CC.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CC.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CC.Domain.Entities.User", b =>
                {
                    b.HasOne("CC.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CC.Domain.Entities.Feature", b =>
                {
                    b.Navigation("AvailablePermissions");
                });

            modelBuilder.Entity("CC.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
